
apiVersion: apps/v1
kind: Deployment
metadata:
  name: be
  namespace: default
  labels:
    app: be
spec:
  replicas: 1
  selector:
    matchLabels:
      app: be
  template:
    metadata:
      labels:
        app: be
    spec:
      containers:
        - name: be
          image: 114002956214.dkr.ecr.eu-central-1.amazonaws.com/be:latest
          ports:
            - containerPort: 8000
              protocol: TCP