apiVersion: v1
kind: Service
metadata:
  name: external-lb
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: fe1
    - protocol: TCP
      port: 8000
      targetPort: 8000
      name: be
  selector:
    lbtype: external