
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fancy-fe1
  labels:
    app: fancy-fe1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fancy-fe1
      lbtype: external
  template:
    metadata:
      labels:
        lbtype: external
        app: fancy-fe1
    spec:
      containers:
        - name: fancy-fe1
          image: 114002956214.dkr.ecr.eu-central-1.amazonaws.com/fe1:latest
          ports:
            - containerPort: 8080
              protocol: TCP